name: Deploy

on:
  push:
    branches:
      - master

jobs:  
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable, dev] # {pkgs.versions}
        include:
          - sdk: stable
            run-tests: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup DartSDK
        uses: dart-lang/setup-dart@v1
      
      - run: dart pub get
      - run: dart analyze
      - run: dart test

      - name: generate doc
        run: dart doc --output=./doc

      - name: Upload documentation files
        uses: actions/upload-artifact@v2
        with:
          name: documentation-files
          path: ./doc/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation-files
          path: ./doc/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/
  